// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZOlOQLSlTj4Bl7BRoOL82qqHRwjf2whQ',
    appId: '1:263441436680:web:3d1b6cf1f23c0e5db801bd',
    messagingSenderId: '263441436680',
    projectId: 'billionworks-2bfbf',
    authDomain: 'billionworks-2bfbf.firebaseapp.com',
    storageBucket: 'billionworks-2bfbf.appspot.com',
    measurementId: 'G-0E84KMJJFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPhPfbVO8rq1Wis2eFsfN0YIldUIwyxKo',
    appId: '1:263441436680:android:0af0128e0ad50f23b801bd',
    messagingSenderId: '263441436680',
    projectId: 'billionworks-2bfbf',
    storageBucket: 'billionworks-2bfbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA96C0XHtRWWlKpOLoReekwP0nN0q3iRnU',
    appId: '1:263441436680:ios:46ea29afbd51d143b801bd',
    messagingSenderId: '263441436680',
    projectId: 'billionworks-2bfbf',
    storageBucket: 'billionworks-2bfbf.appspot.com',
    iosBundleId: 'com.example.handymanUser',
  );

}